import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" class="dark">
      <body class="bg-white dark:bg-slate-900" className={inter.className}>
        {children}

        <div class="px-2 flex items-center">
            <div class="overflow-y-auto py-4 whitespace-nowrap flex items-center">
               <a class="dark:text-slate-400 text-gray-600 hover:text-gray-900 transition-all duration-300" href="#">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="size-5">
                    <path strokeLinecap="round" strokeLinejoin="round" d="m2.25 12 8.954-8.955c.44-.439 1.152-.439 1.591 0L21.75 12M4.5 9.75v10.125c0 .621.504 1.125 1.125 1.125H9.75v-4.875c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21h4.125c.621 0 1.125-.504 1.125-1.125V9.75M8.25 21h8.25" />
                </svg>
                </a>
               <span class="mx-2 text-gray-300">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                     <path stroke-linecap="round" stroke-linejoin="round" d="m8.25 4.5 7.5 7.5-7.5 7.5" />
                </svg>
                  </span>
               <a class="dark:text-slate-400 text-gray-600" href="#"> 
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-5">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M12 7.5h1.5m-1.5 3h1.5m-7.5 3h7.5m-7.5 3h7.5m3-9h3.375c.621 0 1.125.504 1.125 1.125V18a2.25 2.25 0 0 1-2.25 2.25M16.5 7.5V18a2.25 2.25 0 0 0 2.25 2.25M16.5 7.5V4.875c0-.621-.504-1.125-1.125-1.125H4.125C3.504 3.75 3 4.254 3 4.875V18a2.25 2.25 0 0 0 2.25 2.25h13.5M6 7.5h3v3H6v-3Z" />
                </svg>
                      </a>
               <span class="mx-2 text-gray-300"><svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                     <path stroke-linecap="round" stroke-linejoin="round" d="m8.25 4.5 7.5 7.5-7.5 7.5" />
                </svg></span>
               <a class=" dark:text-slate-400 text-gray-600" href="#">tech</a>
            </div>
          </div>

          <section class="px-2 lg:flex lg:space-x-2">
            <a class=" w-full lg:w-2/3 bg-gradient-to-tl from-red-500 
            via-purple-500 to-blue-500 hover:to-green-300 bg-violet-300 
            h-96 mb-4 relative inline-block rounded overflow-hidden" href="#">

              <div class="absolute left-0 top-0 w-full h-full z-10 bg-gradient-to-b from-black/10 to-black/70"></div>
              <img class="absolute left-0 top-0 z-0 w-full h-full object-cover" src="/pittsburgh.png" alt="news"/>
              <div class="p-4 absolute bottom-0 l-0 z-20">
                <h2 class="text-4xl font-semibold text-gray-100 leading-tight">
                Lorem Ipsum is simply dummy text of the printing
                </h2>

                <span class="bg-gradient-to-bl from-blue-600 
                to-indigo-600 text-white inline-flex items-center 
                justify-center px-4 py-1 mb-2">React</span>

                <div class="flex mt-3 ">
                  <img class="h-10 w-10 rounded-full mr-2 object-cover " src="https://randomuser.me/api/portraits/men/7.jpg" alt="author"/>
                  <div>
                    <p class="font-semibold text-gray-200 text-sm">John Doe</p>
                    <time class=" text-gray-400">23 august</time>
                  </div>
                </div>

              </div>
            </a>

            <a class=" w-full lg:w-1/3 bg-indigo-300 h-96 mb-4 relative inline-block rounded overflow-hidden" href="#">

            <div class="absolute left-0 top-0 w-full h-full z-10 bg-gradient-to-b from-black/10 to-black/70"></div>
              <img class="absolute left-0 top-0 z-0 w-full h-full object-cover" src="/OIP (1).png" alt="news"/>
              <div class="p-4 absolute bottom-0 l-0 z-20">
                <h2 class="text-4xl font-semibold text-gray-100 leading-tight">
                Lorem Ipsum is simply dummy text of the printing
                </h2>

                <span class="bg-gradient-to-bl from-blue-600 to-indigo-600 text-white 
                inline-flex items-center justify-center px-4 py-1 mb-2">Python</span>

                <div class="flex mt-3 ">
                   
                  <div>
                    <p class="font-semibold text-gray-200 text-sm">John Doe</p>
                    <time class=" text-gray-400">23 august</time>
                  </div>
                </div>

              </div>
            </a>
            
          </section>


        <main class="lg:flex">
          
          <div class="w-full lg:w-2/3">
               <section class="px-2">
            <a class="mb-10 block w-full lg:flex " href="#">
              <img class="w-full lg:w-48 h-45 oppacity-80 lg:mr-4 object-cover" src="/a-bridge.png" alt="news"/>
              <div class="flex flex-col justify-between">
              <div>
                <h3 class=" mb-2 font-bold text-2xl text-gray-700">Lorem Ipsum is simply dummy text of the printing and typesetting</h3>
                <p class="text-gray-700 dark:text-slate-400">Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
              </div>

              <div class="flex mt-3 ">
                  <img class="h-10 w-10 rounded-full mr-2 object-cover " src="https://randomuser.me/api/portraits/women/3.jpg" alt="author"/>
                  <div>
                    <p class="font-semibold text-gray-200 text-sm">John Doe</p>
                    <time class=" text-gray-400">1 august</time>
                  </div>
                </div>

            </div>
            </a>
              

            
            <a class="mb-10 block w-full lg:flex " href="#">
              <img class="w-full lg:w-48 h-45 oppacity-80 lg:mr-4 object-cover" src="/ght.png" alt="news"/>
              <div class="flex flex-col justify-between">
              <div>
                <h3 class=" mb-2 font-bold text-2xl text-gray-700">Lorem Ipsum is simply dummy text of the printing and typesetting</h3>
                <p class="text-gray-700 dark:text-slate-400">Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
              </div>

              <div class="flex mt-3 ">
                  <img class="h-10 w-10 rounded-full mr-2 object-cover " src="https://randomuser.me/api/portraits/women/9.jpg" alt="author"/>
                  <div>
                    <p class="font-semibold text-gray-200 text-sm">John Doe</p>
                    <time class=" text-gray-400">23 august</time>
                  </div>
                </div>

            </div>
            </a>
            
            <a class="mb-10 block w-full lg:flex " href="#">
              <img class="w-full lg:w-48 h-45 oppacity-80 lg:mr-4 object-cover" src="/OIP.png" alt="news"/>
              <div class="flex flex-col justify-between">
              <div>
                <h3 class=" mb-2 font-bold text-2xl text-gray-700">Lorem Ipsum is simply dummy text of the printing and typesetting</h3>
                <p class="text-gray-700 dark:text-slate-400">Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
              </div>

              <div class="flex mt-3 ">
                  <img class="h-10 w-10 rounded-full mr-2 object-cover " src="https://randomuser.me/api/portraits/women/10.jpg" alt="author"/>
                  <div>
                    <p class="font-semibold text-gray-200 text-sm">John Doe</p>
                    <time class=" text-gray-400">23 august</time>
                  </div>
                </div>

            </div>
            </a>
                </section>

                <div class="mt-20 mb-10 ">
                  <ul class="flex justify-center ">
                    <li><a class="pagination-item rounded-l-lg" href="#">Previous</a></li>
                    <li><a class="pagination-item" href="#">1</a></li>
                    <li><a class="pagination-item " href="#">2</a></li>
                    <li><a class="pagination-item" href="#">3</a></li>
                    <li><a class="pagination-item" href="#">4</a></li>
                    <li><a class="pagination-item" href="#">5</a></li>
                    <li><a class="pagination-item" href="#">6</a></li>
                    <li><a class="pagination-item rounded-r-lg" href="#">Next</a></li>
                  </ul>
                </div>
          </div>


          <div class="w-full lg:w-1/3 px-2 md:flex md:space-x-6 lg:block lg:space-x-0">

            <div class="w-full md:w-1/2 lg:w-full mb-5 ">
            <h5 class="font-bold text-lg  text-grey-700 mb-2 uppercase">Popular News</h5>
            <ul>
              <li class="dark:border-transparent dark:hover:border-gray-200 code .
              ">
                <a class="dark:text-slate-400 flex items-center text-gray-600 " href="#">
                  <span class="inline-blok w-4 h-4 mr-4 bg-gradient-to-tr from-green-600 to-green-800"></span>
                  Vue
                  <span class=" dark:text-slate-400 text-gray-500 ml-auto">23 articles</span>
                </a>
              </li>
              <li class="dark:border-transparent dark:hover:border-gray-200 py-4 px-1 border-y border-white transition-all duration-300 hover:border-grey-200">
                <a class="dark:text-slate-400 flex items-center text-gray-600 " href="#">
                  <span class="inline-blok w-4 h-4 mr-4 bg-gradient-to-tr from-orange-600 to-slate-100orange-800"></span>
                  Svelte
                  <span class="dark:text-slate-400 text-gray-500 ml-auto">20 articles</span>
                </a>
              </li>
              <li class="dark:border-transparent dark:hover:border-gray-200 py-4 px-1 border-y border-white transition-all duration-300 hover:border-grey-200">
                <a class="dark:text-slate-400 flex items-center text-gray-600 " href="#">
                  <span class="inline-blok w-4 h-4 mr-4 bg-gradient-to-tr from-red-600 to-green-300"></span>
                  SASS
                  <span class="dark:text-slate-400 text-gray-500 ml-auto">21 articles</span>
                </a>
              </li>
              <li class="dark:border-transparent dark:hover:border-gray-200 py-4 px-1 border-y border-white transition-all duration-300 hover:border-grey-200">
                <a class="dark:text-slate-400 flex items-center text-gray-600 " href="#">
                  <span class="inline-blok w-4 h-4 mr-4 bg-gradient-to-tr from-blue-600 to-red-400"></span>
                  JS
                  <span class="dark:text-slate-400 text-gray-500 ml-auto">19 articles</span>
                </a>
              </li>
            </ul>
          </div>


             <div class="w-full md:w-1/2 lg:w-full">
              <div class="border border-dotted md:hidden lg:block"></div>

            <div class="my-5 md:my-0 lg:my-5">
              <h5 class="dark:text-white font-bold text-lg  text-grey-700 mb-2 uppercase">Subscribe</h5>
               <p class="dark:text-slate-400 text-gray-600 mb-4 ">Subscribe to our newslatter </p>
                <input
                   type="email"
                   placeholder="your email address"
                   class=" text-gray-700 bg-gray-200 p-2 w-full border rounded-t hover:border-gray-500"/>

                  <button class="px-4 py-3 bg-indigo-600 text-white rounded-b w-full hover:bg-indigo-800">Subscribe</button>
            </div>
           
              <div class="border border-dotted"></div>
             </div>
              

          </div>          
        </main>

            

        <footer class="border-t mt-10 py-10 px-2">
          <div class="md:flex">
            <div class="mb-5 w-full md:w-2/5">
              <h6 class="font-semibold text-green-700 mb-4">
                Company
              </h6>
              <ul>
                <li><a class="footer-link" href="#">Home</a></li>
                <li><a class="footer-link" href="#">About</a></li>
                <li><a class="footer-link " href="#">Contact</a></li>
              </ul>
            </div>

            <div class="mb-5 w-full md:w-2/5">
              <h6 class="font-semibold text-green-700 mb-4">
                Content
              </h6>
              <ul>
                <li><a class="footer-link" href="#">Home</a></li>
                <li><a class="footer-link" href="#">About</a></li>
                <li><a class="footer-link" href="#">Documentation</a></li>
              </ul>
            </div>

            <div class="w-full md:w-1/5">
              <h6 class="font-semibold text-green-700 mb-4">
                Contact us
              </h6>
              <ul class="flex">
                <li class="mr-2 "><a class="footer-link" href="#"><svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
  <path stroke-linecap="round" stroke-linejoin="round" d="M8.625 12a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0Zm0 0H8.25m4.125 0a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0Zm0 0H12m4.125 0a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0Zm0 0h-.375M21 12c0 4.556-4.03 8.25-9 8.25a9.764 9.764 0 0 1-2.555-.337A5.972 5.972 0 0 1 5.41 20.97a5.969 5.969 0 0 1-.474-.065 4.48 4.48 0 0 0 .978-2.025c.09-.457-.133-.901-.467-1.226C3.93 16.178 3 14.189 3 12c0-4.556 4.03-8.25 9-8.25s9 3.694 9 8.25Z" />
</svg>
</a></li>
                <li class="mr-2 "><a class="footer-link" href="#"><svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
  <path stroke-linecap="round" stroke-linejoin="round" d="M16.5 12a4.5 4.5 0 1 1-9 0 4.5 4.5 0 0 1 9 0Zm0 0c0 1.657 1.007 3 2.25 3S21 13.657 21 12a9 9 0 1 0-2.636 6.364M16.5 12V8.25" />
</svg>
</a></li>
                <li><a class="footer-link" href="#"><svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
  <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 6.75c0 8.284 6.716 15 15 15h2.25a2.25 2.25 0 0 0 2.25-2.25v-1.372c0-.516-.351-.966-.852-1.091l-4.423-1.106c-.44-.11-.902.055-1.173.417l-.97 1.293c-.282.376-.769.542-1.21.38a12.035 12.035 0 0 1-7.143-7.143c-.162-.441.004-.928.38-1.21l1.293-.97c.363-.271.527-.734.417-1.173L6.963 3.102a1.125 1.125 0 0 0-1.091-.852H4.5A2.25 2.25 0 0 0 2.25 4.5v2.25Z" />
</svg>
</a></li>
              </ul>
            </div>
          </div>
        </footer>
        </body>
    </html>
  );
}
